packages:
  - apps/*
  - packages/*
  - services/*
  - tests/*

overrides:
  fast-uri@3: ^3.1.4
  ioredis: ^5.11.1
  js-yaml@4: ^4.3.0
  sharp: ^0.35.0
  ws: ^8.21.0

allowBuilds:
  '@apollo/protobufjs': false
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  msgpackr-extract: true
  prisma: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@scarf/scarf'
  - protobufjs
