envVarGroups:
  - name: paymock-shared
    envVars:
      - key: PAYMOCK_API_KEY
        generateValue: true
      - key: PAYMOCK_WEBHOOK_SECRET
        generateValue: true

services:
  - type: web
    name: openseat-api
    runtime: node
    plan: free
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm --filter api db:generate && pnpm --filter api build && pnpm --filter api db:migrate:deploy && node apps/api/dist/seed.js
    startCommand: node apps/api/dist/main.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: '22.18.0'
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_ORIGIN
        sync: false
      - key: APP_VERSION
        value: m2
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: openseat-redis
          property: connectionString
      - key: PAYMOCK_URL
        value: https://openseat-paymock.onrender.com
      - key: API_PUBLIC_URL
        value: https://openseat-api.onrender.com
      - fromGroup: paymock-shared

  - type: web
    name: openseat-paymock
    runtime: go
    plan: free
    rootDir: services/paymock
    buildCommand: go build -o paymock .
    startCommand: ./paymock
    healthCheckPath: /health
    envVars:
      - key: PAYMOCK_PUBLIC_URL
        value: https://openseat-paymock.onrender.com
      - fromGroup: paymock-shared

  - type: keyvalue
    name: openseat-redis
    plan: free
    ipAllowList: []
